language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.8
      env:
        - TF_ACC=true

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
- go get -d github.com/hashicorp/terraform
- ls $GOPATH
- cd $GOPATH/src/github.com/hashicorp/terraform
- git checkout tags/0-8-stable
- go install github.com/hashicorp/terraform

script:
- go test -v ./plugin/providers/keboola/
