language: go

branches:
  only:
    - master

matrix:
  include:
    - go: 1.8
      env:
        - TF_ACC=true

install:
- go get -d github.com/hashicorp/terraform
- go get github.com/stretchr/testify
- ls $GOPATH
- cd $GOPATH/src/github.com/hashicorp/terraform
- git checkout tags/v0.8.8
- go install github.com/hashicorp/terraform
- go install github.com/stretchr/testify
- cd $GOPATH/src/github.com/plmwong/terraform-provider-keboola

script:
- go test -v ./plugin/providers/keboola/
